### ISSUE TITLE
Log Daily Journal

### ISSUE THREAD

**Issue by SaraMathews** [SaraMathews/My-Healthy-Mind#1]
As a **user**, I want to **log my Daily Journal for a selected day** so that **I can keep a record of my thoughts and feelings over time.**

**Acceptance Criteria**
1. The user should be able to click the "Daily Journal" button in the navbar on the Home Page. 
2. The user should be able to select a specific date for their journal entry.
3. The user should be able to enter the content for the new journal entry.
4. The user should be able to, at any point, discard the journal entry in progress. 
5. The journal entry should be saved to the user's account.

**Tasks**
- [x] Create the template that will display the Daily Journal form. 
- [x] In the navbar, create a link that brings the user to the Daily Journal Page when clicked.
- [x] In models.py, add the method to the appropriate model class representing the Daily Journal.
- [x] In views.py, create the view function that handles the Daily Journal submit button request. 
- [x] In urls.py, add the appropriate URL pattern that handles the request for submitting the journal entry.
