### ISSUE TITLE
Deployment to Heroku

### ISSUE THREAD

**Issue by SaraMathews** [SaraMathews/My-Healthy-Mind#14]
As a **developer**, I want to **deploy my project to Heroku** so that **it will be accessible to users on the web**

**Acceptance Criteria**
1. The project is successfully deployed and accessible on Heroku.
2. The deployed app must function properly.
3. The deployed app must have the necessary Config Vars set in the setting on Heroku
.  

**Tasks**
- [x] Create a new app on Heroku.
- [x] Configure the project in CodeAnywhere for deployment on Heroku.
- [x] Connect app to GitHub
- [x] Deploy the Healthy Mind Project to Heroku
- [x] Verify and test the deployed app
- [x] Add/remove the necessary Config Vars
