### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by SaraMathews** [SaraMathews/My-Healthy-Mind#15]
As a **developer**, I want **to create a comprehensive README file for the project** to  **provide concise and helpful information for users and assessors**

**Acceptance Criteria**
1. The README file should be created and well-structured with all the necessary sections.
2. Each section of the README file should contain relevant information.
3. The README file should be well-formatted, easy to read and have few (if no) grammatical errors.

**Tasks**
- [x] Add the "Description"  section with a concise and informative project description 
- [x] Add the "UX and Design"  section with a Mind map and Wireframe.
- [x] Add the "Features" section that lists and describes each feature of the website along with a corresponding image of the feature.
- [x] Add the "User Stories" section, which documents the user stories for the Healthy Mind website.
- [x] Add the "Testing" section containing the subsections: Performance, Validator testing, Functional testing and Unfixed bugs.
- [x] Add the "Technologies" section listing all the technologies used for the project
- [x] Add the "Deployment" section with the subsections: Version control, Deploy to Heroku and Clone the Repository from GitHub.
- [x] Add the "Credit" section.
