### ISSUE TITLE
Cancel Edit or Deletion of Journal

### ISSUE THREAD

**Issue by SaraMathews** [SaraMathews/My-Healthy-Mind#16]
As a **user **, I can **cancel an ongoing edit or deletion of a journal,** so  **if I change my mind, I can easily be redirected back to the previous page. **

**Acceptance Criteria**
1. When the user is on the edit page of a journal, they should have the option to click the Cancel button.
2. When the user is on the confirm deletion page, they should have the option to click the Cancel button.
3. When the Cancel button is clicked, they are redirected back to the View Past Journals page.

**Tasks**
- [ ] Create the Cancel button for the confirm deletion page and the edit page. 
- [ ] Add an onclick event to the Cancel button.
- [ ] Add a Javascript function to redirect the user to the previous page.
