### ISSUE TITLE
View past journals

### ISSUE THREAD

**Issue by SaraMathews** [SaraMathews/My-Healthy-Mind#2]
As a **user**, I want **to be able to view past journal entries** so that **I can revisit and reflect on my previous days' thoughts and feelings.**

**Acceptance Criteria**
1. The previously added entries should be displayed as a list underneath the Daily Journal form.
2. The user should be able to click on the collapsed entries below the journal form to expand them and view the content.
3. The entries should be displayed in order starting from the last journal added (reverse chronological order).

**Tasks**
- [x] Create the template that will display all of the user's past journal entries.
- [x] In modals.py, add a method to the appropriate model that allows the user to view past entries in reverse chronological order.
- [x] In views.py, create the view function to handle the "view past journals" request.
- [x] In urls.py, add the appropriate URL pattern for viewing past journals.
