### ISSUE TITLE
Edit Journal entry 

### ISSUE THREAD

**Issue by SaraMathews** [SaraMathews/My-Healthy-Mind#3]
As a **user**, I want **to be able to edit a journal entry** so that **I can fix any mistakes or add more content.**

**Acceptance Criteria**
1. The user should be able to click the "Edit" button on each logged journal entry.
2. The journal form should then display so the user can edit the journal entry's content.
3. When the user clicks "Save changes", the changes should be saved to the journal entry.

**Tasks**
- [x] Create an "Edit" button on the previously added entries.
- [x] Create a template that will display the edit journal form.
- [x] In modals.py, update the method on the appropriate model class that allows the user to edit a specific entry.
- [x] In views.py, create the view function to handle the edit request when the user clicks "Edit".
- [x] In urls.py, add the appropriate URL pattern for editing the journal.
