### ISSUE TITLE
Delete Journal entry 

### ISSUE THREAD

**Issue by SaraMathews** [SaraMathews/My-Healthy-Mind#4]
As a **user**, I want  **to be able to delete a previously added journal entry** so that **I can remove specific journals from my logged journals if I wish**

**Acceptance Criteria**
1. The user should be able to click the "Delete" button on each logged entry.
2. The user should have to confirm they want to delete the selected journal entry. 
3. The selected journal entry should be removed from the entries list and deleted from the database.

**Tasks**
- [x] Create a "Delete" button on the previously added entries.
- [x] In modals.py, update the method on the appropriate model class that allows the user to delete a specific entry.
- [x] In views.py, create the view function to handle the delete request when the user clicks "Delete".
- [x]  In urls.py, add the appropriate URL pattern for deleting the journal.
- [x] Add defensive programming so when the user clicks "Delete", they must confirm.
