### ISSUE TITLE
View Home Page 

### ISSUE THREAD

**Issue by SaraMathews** [SaraMathews/My-Healthy-Mind#5]
As a **user**, I can **view the content on the Home Page** so that **I can gain a sense of what the website offers.**

**Acceptance Criteria**
1. The user should be able to view the image and welcoming message.
2. The user should be able to view the navbar and footer. 

**Tasks**
- [x] Create the template that will display the Home Page.
- [x] Add a section with a welcoming message that introduces the website to the user.
- [x] Create the navbar and footer.
