### ISSUE TITLE
Admin - updating Daily Quotes 

### ISSUE THREAD

**Issue by SaraMathews** [SaraMathews/My-Healthy-Mind#6]
As an **admin**, I can **add new quotes to the database** so that **the user can see daily quotes each time they visit the website.**

**Acceptance Criteria**
1. The admin should be able to log in to the admin page. 
2. The admin should be able to fill out a form with the new quotes.
3. The quotes should be saved to the database.

**Tasks**
- [x] Create the admin page for quotes and user management. 
- [x] Create the template that will display the quotes.
- [x] In modals.py, add the method to the appropriate model class representing the Daily Quotes.
- [x] Update admin.py with the Daily Quotes model.
- [x] Update views.py to save the quote to the database
- [x] In urls.py, add the appropriate URL pattern for the quote form.
